### ISSUE TITLE
[Bug] Volumes not working

### ISSUE THREAD

**Issue by AlexanderLieret** [DeineAgenturUG/greenbone-gvm-openvas-for-docker#20]
**Describe the bug**
When using volume bindings, the initialization and updates are not working.

**To Reproduce**
Start GVM with this docker-compose.yml. All image variants have the same problem.
```yml
version: "3"
services:
    gvm:
        image: deineagenturug/gvm:latest-full
        #image: deineagenturug/gvm:latest-data-full
        #image: deineagenturug/gvm:latest
        volumes:
          - ./data-postgres:/opt/database
          - ./data-gvm:/var/lib/gvm
          - ./data-plugins:/var/lib/openvas/plugins
          - ./data-ssh:/etc/ssh
        environment:
          - USERNAME="admin"
          - PASSWORD="admin"
          - RELAYHOST="smtp"
          - SMTPPORT=25
          - AUTO_SYNC=true
          - HTTPS=true
          - TZ="UTC"
          - SSHD=false
          - DB_PASSWORD="none"
        ports:
          - "8080:9392"  # Web interface
          #- "2222:22"   # SSH for remote sensors
        restart: unless-stopped
```

**Expected behavior**
Container starts and initializes the database, like running

```bash
docker run --rm -p 8080:9392 deineagenturug/gvm:latest-data-full
```

**Screenshots**
```
# tail /var/log/gvm/gvmd.log
md   main:WARNING:2022-04-25 11h05.15 utc:732: The gvmd data feed directory /var/lib/gvm/data-objects/gvmd or one of its subdirectories does not exist.
md manage:WARNING:2022-04-25 11h05.15 utc:761: update_scap: No SCAP db present, rebuilding SCAP db from scratch
md manage:   INFO:2022-04-25 11h05.15 utc:762: OSP service has different VT status (version 0) from database (version (null), 0 VTs). Starting update ...
md manage:   INFO:2022-04-25 11h05.15 utc:763: Initializing CERT database
md manage:   INFO:2022-04-25 11h05.16 utc:762: Updating VTs in database ... 0 new VTs, 0 changed VTs
md manage:   INFO:2022-04-25 11h05.16 utc:762: Updating VTs in database ... done (0 VTs).
md manage:   INFO:2022-04-25 11h05.16 utc:761: update_scap: Updating data from feed
md manage:WARNING:2022-04-25 11h05.16 utc:761: update_scap_cpes: No CPE dictionary found at /var/lib/gvm/scap-data/official-cpe-dictionary_v2.2.xml
md   main:MESSAGE:2022-04-25 11h05.25 utc:773:    Greenbone Vulnerability Manager version 21.4.5 (DB revision 242)
md manage:   INFO:2022-04-25 11h05.25 utc:773:    Getting users.
md manage:MESSAGE:2022-04-25 11h05.25 utc:773: No SCAP database found
md   main:MESSAGE:2022-04-25 11h05.25 utc:777:    Greenbone Vulnerability Manager version 21.4.5 (DB revision 242)
md manage:   INFO:2022-04-25 11h05.25 utc:777:    Creating user.
md manage:MESSAGE:2022-04-25 11h05.25 utc:777: No SCAP database found
md   main:MESSAGE:2022-04-25 11h05.25 utc:781:    Greenbone Vulnerability Manager version 21.4.5 (DB revision 242)
md manage:   INFO:2022-04-25 11h05.25 utc:781:    Getting users.
md manage:MESSAGE:2022-04-25 11h05.25 utc:781: No SCAP database found
md   main:MESSAGE:2022-04-25 11h05.25 utc:785:    Greenbone Vulnerability Manager version 21.4.5 (DB revision 242)
md manage:   INFO:2022-04-25 11h05.25 utc:785:    Modifying setting.
md manage:MESSAGE:2022-04-25 11h05.25 utc:785: No SCAP database found
md   main:MESSAGE:2022-04-25 11h05.25 utc:789:    Greenbone Vulnerability Manager version 21.4.5 (DB revision 242)
md manage:   INFO:2022-04-25 11h05.25 utc:789:    Modifying scanner.
md manage:MESSAGE:2022-04-25 11h05.25 utc:789: No SCAP database found
md   main:MESSAGE:2022-04-25 11h05.25 utc:805:    Greenbone Vulnerability Manager version 21.4.5 (DB revision 242)
md manage:   INFO:2022-04-25 11h05.25 utc:805:    Modifying scanner.
md manage:MESSAGE:2022-04-25 11h05.25 utc:805: No SCAP database found
md manage:WARNING:2022-04-25 11h05.26 utc:827: update_scap: No SCAP db present, rebuilding SCAP db from scratch
md manage:   INFO:2022-04-25 11h05.26 utc:827: update_scap: Updating data from feed
md manage:WARNING:2022-04-25 11h05.26 utc:827: update_scap_cpes: No CPE dictionary found at /var/lib/gvm/scap-data/official-cpe-dictionary_v2.2.xml
md manage:WARNING:2022-04-25 11h05.36 utc:839: update_scap: No SCAP db present, rebuilding SCAP db from scratch
md manage:   INFO:2022-04-25 11h05.36 utc:839: update_scap: Updating data from feed
md manage:WARNING:2022-04-25 11h05.36 utc:839: update_scap_cpes: No CPE dictionary found at /var/lib/gvm/scap-data/official-cpe-dictionary_v2.2.xml
md manage:WARNING:2022-04-25 11h05.46 utc:852: update_scap: No SCAP db present, rebuilding SCAP db from scratch
md manage:   INFO:2022-04-25 11h05.46 utc:852: update_scap: Updating data from feed
md manage:WARNING:2022-04-25 11h05.46 utc:852: update_scap_cpes: No CPE dictionary found at /var/lib/gvm/scap-data/official-cpe-dictionary_v2.2.xml
```

**Host Device:**
 - OS: Debian 11
 - Version: Docker version 20.10.14, build a224086

**Image in use:**
- Self build? - No
- Output from `docker image ls deineagenturug/gvm` :
  ```
  docker image ls deineagenturug/gvm
  REPOSITORY           TAG                IMAGE ID       CREATED       SIZE
  deineagenturug/gvm   latest-data-full   c4d21b815e60   2 weeks ago   5.68GB
  deineagenturug/gvm   latest-full        93b98fade506   2 weeks ago   965MB
  deineagenturug/gvm   latest               701b1aaeb107   2 weeks ago    676MB
  ```

**Additional context**
